Description: >
    This stack contains the information for the creation of a EKS node and associate it to the cluster

Parameters:

    EnvironmentName:
        Description: Name of the environment for Capstone Project
        Type: String

Resources:

    ##Role configuration

    #Role
    NodeInstanceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - ec2.amazonaws.com
                      Action:
                        - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
                - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
                - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
            Path: /
            RoleName: NodeInstanceRole    
    
   
    EKSManagedNodeGroup:
        Type: AWS::EKS::Nodegroup
        Properties: 
            AmiType: AL2_x86_64
            ClusterName: final-project-udacity-my-real-test
            InstanceTypes: 
                - t2.small
            NodegroupName: final-project-udacity-my-real-test-nodes
            NodeRole: !GetAtt 
                - NodeInstanceRole
                - Arn
            ScalingConfig: 
                DesiredSize: 1
                MaxSize: 1
                MinSize: 1
            Subnets: !Split 
                - ','
                - !ImportValue frenandi-EKS-Final-Project-PublicSubnets